version: '2'

services:
  dnsmasq:
    container_name: harpoon_dnsmasq
    build: core/dnsmasq
    environment:
      - USER=dev
      - PASS=harpoon
      - NAMESERVER_IP
      - CUSTOM_DOMAIN
    ports:
      - "53:53/udp"
      - "5380:8080"
    logging:
      options:
        max-size: 100m

  cadvisor:
    container_name: harpoon_cadvisor
    image: google/cadvisor:latest
    ports:
      - "8070:8080"
    labels:
      - "traefik.backend=cadvisor"
      - "traefik.port=8080"
      - "traefik.frontend.rule=Host:${CADVISOR_HOSTS}"
      - "traefik.frontend.entryPoints=${FRONTEND_ENTRYPOINTS}"
      - "traefik.docker.network=${HARPOON_DOCKER_NETWORK}"
      - "traefik.tags=${TRAEFIK_DOCKER_TAGS}"
    networks:
      default:
        aliases:
          - cadvisor.harpoon.dev
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro

  consul:
    container_name: harpoon_consul
    image: progrium/consul
    command: -server -bootstrap -log-level debug -ui-dir /ui
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:53/udp"
    expose:
      - "8300"
      - "8301"
      - "8301/udp"
      - "8302"
      - "8302/udp"
    labels:
      - "traefik.backend=consul"
      - "traefik.port=8500"
      - "traefik.frontend.rule=Host:${CONSUL_HOSTS}"
      - "traefik.frontend.entryPoints=${FRONTEND_ENTRYPOINTS}"
      - "traefik.docker.network=${HARPOON_DOCKER_NETWORK}"
      - "traefik.tags=${TRAEFIK_DOCKER_TAGS}"
    networks:
      default:
        aliases:
          - consul.harpoon.dev

  traefik:
    container_name: harpoon_traefik
    image: traefik:1.2.3
    command: ${TRAEFIK_COMMAND}
    environment:
    # cloudflare
      - CLOUDFLARE_EMAIL
      - CLOUDFLARE_API_KEY
    # digitalocean
      - DO_AUTH_TOKEN
    # dnsimple
      - DNSIMPLE_EMAIL
      - DNSIMPLE_API_KEY
    # dnsmadeeasy
      - DNSMADEEASY_API_KEY
      - DNSMADEEASY_API_SECRET
    # exoscale
      - EXOSCALE_API_KEY
      - EXOSCALE_API_SECRET
    # gandi
      - GANDI_API_KEY
    # linode
      - LINODE_API_KEY
    # namecheap
      - NAMECHEAP_API_USER
      - NAMECHEAP_API_KEY
    # rfc2136
      - RFC2136_TSIG_KEY
      - RFC2136_TSIG_SECRET
      - RFC2136_TSIG_ALGORITHM
      - RFC2136_NAMESERVER
    # route53
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_REGION
    # dyn
      - DYN_CUSTOMER_NAME
      - DYN_USER_NAME
      - DYN_PASSWORD
    # vultr
      - VULTR_API_KEY
    # ovh
      - OVH_ENDPOINT
      - OVH_APPLICATION_KEY
      - OVH_APPLICATION_SECRET
      - OVH_CONSUMER_KEY
    # pdns
      - PDNS_API_KEY
      - PDNS_API_URL
    ports:
      - "${TRAEFIK_HTTP_PORT}:80"
      - "${TRAEFIK_HTTPS_PORT}:443"
      - "8075"
    links:
      - consul
    labels:
      - "traefik.backend=traefik"
      - "traefik.port=8075"
      - "traefik.frontend.rule=Host:${TRAEFIK_HOSTS}"
      - "traefik.frontend.entryPoints=${FRONTEND_ENTRYPOINTS}"
      - "traefik.docker.network=${HARPOON_DOCKER_NETWORK}"
      - "traefik.tags=${TRAEFIK_DOCKER_TAGS}"
    networks:
      default:
        aliases:
          - traefik.harpoon.dev
    volumes:
      - ./core/traefik/:/etc/traefik/
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  default:
    external:
      name: ${HARPOON_DOCKER_NETWORK}