version: '2'

services:
  elk:
    container_name: harpoon_elk
    image: sebp/elk
    environment:
      - TERM=xterm
    labels:
      - "traefik.backend=elk"
      - "traefik.port=5601"
      - "traefik.frontend.rule=Host:${ELK_HOSTS}"
      - "traefik.frontend.entryPoints=${FRONTEND_ENTRYPOINTS}"
      - "traefik.docker.network=${HARPOON_DOCKER_NETWORK}"
      - "traefik.tags=${TRAEFIK_DOCKER_TAGS}"
    networks:
      default:
        aliases:
          - elk.harpoon
    ports:
      - "5601"
      - "9200:9200"
      - "5044:5044"

networks:
  default:
    external:
      name: ${HARPOON_DOCKER_NETWORK}