version: '2'

services:
  mysql:
    image: mysql:${MYSQL_VERSION}
    environment:
      - TERM=xterm
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - /var/lib/mysql:/var/lib/mysql

networks:
  default:
    external:
      name: ${HARPOON_DOCKER_NETWORK}